name: Test Execution in QA
'on':
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: temurin
          cache: maven
      - name: Build with Maven
        run: mvn clean test -DforkCount=0 test -Denv=QA --file pom.xml
      - name: Upload Test Results
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: Test Results
          path: test output/PdfReport/ExtentPdf.pdf
      - name: Archive test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: target/
